name: wan_android
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  cookie_jar: ^3.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  path_provider: ^2.0.8
  logging: ^1.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  freezed_annotation: ^1.0.0
  flutter_riverpod: ^1.0.0
  pull_to_refresh: ^2.0.0
  flutter_svg: ^1.0.0
  beamer: ^1.1.0
  extended_sliver: ^2.0.1
  intl: ^0.17.0
  extended_image: ^6.0.1
  palette_generator: ^0.3.2
  flutter_smart_dialog: ^3.1.0
  animated_flip_counter: ^0.2.1
  flutter_inappwebview: ^5.3.2
  connectivity_plus: ^2.2.0
  flutter_slidable: ^1.2.0
  shimmer: ^2.0.0
  html: ^0.15.0
  url_launcher: ^6.0.18
  custom_pop_up_menu: ^1.2.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.5
  freezed: ^1.1.0
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true

  assets:

  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by https://github.com/fluttercandies/assets_generator
  # **************************************************************************

    - assets/images/

  # assets end
  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/icon_font.ttf

flutter_intl:
  enabled: true
  arb_dir: lib/app/l10n
  output_dir: lib/app/l10n/generated